l_italian:
 CK3DISPLAYNAME: "da Crusader Kings III a Europa Universalis IV"
 CK3GAME: "Crusader Kings III"
 EU4GAME: "Europa Universalis IV"
 CK3FOLDER: "Cartella di installazione di Crusader Kings III"
 CK3FOLDERTIP: "Il percorso in cui è installato Crusader Kings III"
 CK3MOD: "Cartella delle mod per Crusader Kings III"
 CK3MODTIP: "Il percorso in cui Crusader Kings III memorizza le mod"
 EU4FOLDER: "Cartella di installazione di Europa Universalis IV"
 EU4FOLDERTIP: "Il percorso in cui è installato Europa Universalis IV"
 CK3FILE: "Percorso dell'eseguibile del convertitore"
 CK3FILETIP: "Percorso di CK3ToEU4Converter.exe"
 CK3SAVE: "Percorso del savegame CK3"
 CK3SAVETIP: "Percorso per il tuo savegame da CK3"
 CK3DOC: "Cartella dei documenti di Crusader Kings III"
 CK3DOCTIP: "Un percorso in cui Crusader Kings III conserva file temporanei"
 EU4MOD: "Cartella delle mod per Europa Universalis IV"
 EU4MODTIP: "Il percorso in cui Europa Universalis IV memorizza le mod"
