l_russian:
 CK3DISPLAYNAME: "из Crusader Kings III в Европу Универсалис IV"
 CK3GAME: "Crusader Kings III"
 EU4GAME: "Европа Универсалис IV"
 CK3FOLDER: "Crusader Kings II Установить каталог"
 CK3FOLDERTIP: "Путь на вашем компьютере, где установлен Crusader Kings III"
 CK3MOD: "Crusader Kings III Мод Каталог"
 CK3MODTIP: "Путь на вашем компьютере, где хранятся моды Crusader Kings III"
 EU4FOLDER: "Европа Универсалис IV Установить каталог"
 EU4FOLDERTIP: "Путь на вашем компьютере, где установлена Европа Универсалис IV"
 CK3FILE: "Путь к исполняемому файлу конвертера"
 CK3FILETIP: "Путь к CK3ToEU4Converter.exe"
 CK3SAVE: "Путь к сохранению игры CK3"
 CK3SAVETIP: "Путь к вашей сохраненной игре от CK3"
 CK3DOC: "Справочник документов Европа Crusader Kings III"
 CK3DOCTIP: "Путь на вашем компьютере, где Европа Crusader Kings III хранит временные файлы"
 EU4MOD: "Европа Универсалис IV Мод Каталог"
 EU4MODTIP: "Путь на вашем компьютере, где хранятся моды Европа Универсалис IV"

