l_german:
 CK2DISPLAYNAME: "von Crusader Kings II zu Europa Universalis IV"
 EU4DISPLAYNAME: "von Europa Universalis IV zu Victoria II"
 VIC2DISPLAYNAME: "von Victoria II zu Hearts of Iron IV"
 CK2GAME: "Crusader Kings II"
 EU4GAME: "Europa Universalis IV"
 VIC2GAME: "Victoria II"
 HOI4GAME: "Hearts of Iron IV"
 CK2FOLDER: "Crusader Kings II-Installationsverzeichnis"
 CK2FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Crusader Kings II installiert ist"
 CK2MOD: "Crusader Kings II Mod-Verzeichnis"
 CK2MODTIP: "Der Pfad auf Ihrem Computer, auf dem Crusader Kings II Mods speichert"
 EU4FOLDER: "Europa Universalis IV-Installationsverzeichnis"
 EU4FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Europa Universalis IV installiert ist"
 EU4MOD: "Europa Universalis IV Steam Workshop Mod-Verzeichnis"
 EU4MODTIP: "Der Pfad auf Ihrem Computer, auf dem Europa Universalis IV Steam Mods speichert"
 VIC2FOLDER: "Victoria II-Installationsverzeichnis"
 VIC2FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Victoria II installiert ist"
 VIC2MOD: "Victoria II Mod-Verzeichnis"
 VIC2MODTIP: "Der Pfad auf Ihrem Computer, auf dem Victoria II Mods speichert"
 HOI4FOLDER: "Hearts of Iron IV-Installationsverzeichnis"
 HOI4FOLDERTIP: "Der Pfad auf Ihrem Computer, auf dem Hearts of Iron IV installiert ist"
 HOI4MOD: "Hearts of Iron IV Mod-Verzeichnis"
 HOI4MODTIP: "Der Pfad auf Ihrem Computer, auf dem Hearts of Iron IV Mods speichert"
 CK2FILE: "Pfad zur ausführbaren Datei des Konverters"
 CK2FILETIP: "Pfad zu CK2ToEU4Converter.exe"
 CK2SAVE: "Pfad zum CK2-Savegame"
 CK2SAVETIP: "Pfad zu Ihrem Savegame von CK2"
 EU4FILE: "Pfad zur ausführbaren Datei des Konverters"
 EU4FILETIP: "Pfad zu EU4ToVic2Converter.exe"
 EU4SAVE: "Pfad zum EU4-Savegame"
 EU4SAVETIP: "Pfad zu Ihrem Savegame von EU4"
 VIC2FILE: "Pfad zur ausführbaren Datei des Konverters"
 VIC2FILETIP: "Pfad zu Vic2ToHoI4Converter.exe"
 VIC2SAVE: "Pfad zum Vic2-Savegame"
 VIC2SAVETIP: "Pfad zu Ihrem Savegame von Vic2"
 EU4DOC: "Europa Universalis IV-Dokumentenverzeichnis"
 EU4DOCTIP: "Ein Pfad auf Ihrem Computer, in dem Europa Universalis IV temporäre Dateien speichert"
 CK2EXP: "Crusader Kings II Exportverzeichnis"
 CK2EXPTIP: "(Optional) Ein Pfad auf Ihrem Computer, in dem Crusader Kings II exportierte Spiele speichert"
 VIC2DOC: "Victoria II-Dokumentenverzeichnis"
 VIC2DOCTIP: "Ein Pfad auf Ihrem Computer, in dem Victoria II temporäre Dateien speichert"