version: dev.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild -m CK3toEU4.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- ps: >-
    cd CK3ToEU4Tests\Release

    .\CK3ToEU4Tests.exe --gtest_output=xml:tests.xml

    (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
artifacts:
- path: Release
  name: CK3toEU4-0.4dynamic
deploy:
- provider: GitHub
  release: windows_development_build
  description: The most recent build of the development version
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: ParadoxGameConverters/CK3ToEU4
  artifact: CK3toEU4-0.4dynamic
  prerelease: true
  force_update: true
